# Generated by Django 2.2.10 on 2021-08-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор пользователя'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ManyToManyField(related_name='questionnaire', to='questionnaire.Questionnaire'),
        ),
    ]
